import { Deal } from "@/types/deal";

const now = new Date("2026-06-25T12:00:00Z");

function daysFromNow(days: number): string {
  const d = new Date(now);
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

function hoursFromNow(hours: number): string {
  const d = new Date(now);
  d.setHours(d.getHours() + hours);
  return d.toISOString();
}

function daysAgo(days: number): string {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

export const mockDeals: Deal[] = [
  {
    id: "deal-001",
    retailer: "Sephora",
    retailerNormalized: "sephora",
    category: "Beauty & Cosmetics",
    offerType: "percentage_off",
    dealColor: "purple",
    discountValue: 50,
    discountUnit: "percent",
    promoCode: "BEAUTY50",
    minimumSpend: 100,
    restrictions: "Excludes skincare sets and gift cards",
    expirationDate: hoursFromNow(36),
    expirationStatus: "expiring_soon",
    urgency: "urgent",
    confidenceScore: "high",
    sourceEmail: {
      subject: "50% Off Sitewide — Today & Tomorrow Only",
      receivedAt: daysAgo(1),
      senderDomain: "email.sephora.com",
    },
    status: "active",
    qualityScore: 96,
    effectiveDiscountPercent: 50,
    notes: "",
    brands: ["Fenty Beauty", "Charlotte Tilbury", "Rare Beauty"],
  },
  {
    id: "deal-002",
    retailer: "Nike",
    retailerNormalized: "nike",
    category: "Clothing & Apparel",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 30,
    discountUnit: "percent",
    promoCode: "SUMMER30",
    minimumSpend: null,
    restrictions: "Member exclusive. Excludes Jordan Brand.",
    expirationDate: daysFromNow(5),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "Members Only: 30% Off Sitewide",
      receivedAt: daysAgo(2),
      senderDomain: "news.nike.com",
    },
    status: "active",
    qualityScore: 89,
    effectiveDiscountPercent: 30,
    notes: "",
    brands: ["Nike", "Air Max"],
  },
  {
    id: "deal-003",
    retailer: "Whole Foods",
    retailerNormalized: "wholefoods",
    category: "Grocery & Food",
    offerType: "bogo",
    dealColor: "green",
    discountValue: 50,
    discountUnit: "bogo",
    promoCode: null,
    minimumSpend: null,
    restrictions: "Prime member deal. Valid in-store only.",
    expirationDate: daysFromNow(3),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "This Week's Prime Member Deals at Whole Foods",
      receivedAt: daysAgo(1),
      senderDomain: "amazon.com",
    },
    status: "active",
    qualityScore: 87,
    effectiveDiscountPercent: 50,
    notes: "BOGO on all organic produce",
    brands: ["365 Everyday Value"],
  },
  {
    id: "deal-004",
    retailer: "Apple",
    retailerNormalized: "apple",
    category: "Tech & Electronics",
    offerType: "dollar_off",
    dealColor: "orange",
    discountValue: 200,
    discountUnit: "dollars",
    promoCode: "BACKTOSCHOOL",
    minimumSpend: null,
    restrictions: "Education pricing. Requires .edu email or school ID.",
    expirationDate: daysFromNow(12),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "Back to School: Save $200 on Mac + Free AirPods",
      receivedAt: daysAgo(3),
      senderDomain: "apple.com",
    },
    status: "active",
    qualityScore: 94,
    effectiveDiscountPercent: 14,
    notes: "Includes free AirPods with qualifying Mac purchase",
  },
  {
    id: "deal-005",
    retailer: "DoorDash",
    retailerNormalized: "doordash",
    category: "Fast Food & Restaurants",
    offerType: "free_shipping",
    dealColor: "teal",
    discountValue: 0,
    discountUnit: "free",
    promoCode: "DASHFREE",
    minimumSpend: 15,
    restrictions: "First 3 orders. New users only.",
    expirationDate: daysFromNow(30),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "Free delivery on your next 3 orders",
      receivedAt: daysAgo(4),
      senderDomain: "doordash.com",
    },
    status: "active",
    qualityScore: 78,
    effectiveDiscountPercent: 15,
    notes: "",
  },
  {
    id: "deal-006",
    retailer: "Nordstrom Rack",
    retailerNormalized: "nordstromrack",
    category: "Clothing & Apparel",
    offerType: "clearance_sale",
    dealColor: "yellow",
    discountValue: 70,
    discountUnit: "percent",
    promoCode: null,
    minimumSpend: null,
    restrictions: "In-store and online. While supplies last.",
    expirationDate: hoursFromNow(18),
    expirationStatus: "expiring_soon",
    urgency: "urgent",
    confidenceScore: "high",
    sourceEmail: {
      subject: "CLEAR THE RACK — Extra 70% Off Clearance Ends Tonight",
      receivedAt: daysAgo(1),
      senderDomain: "nordstromrack.com",
    },
    status: "active",
    qualityScore: 91,
    effectiveDiscountPercent: 70,
    notes: "Clearance event — Levi's, Calvin Klein, and more",
    brands: ["Levi's", "Calvin Klein", "Tommy Hilfiger"],
  },
  {
    id: "deal-007",
    retailer: "Adobe",
    retailerNormalized: "adobe",
    category: "Subscriptions & SaaS",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 40,
    discountUnit: "percent",
    promoCode: "CREATIVEPRO40",
    minimumSpend: null,
    restrictions: "First year only. Annual plan required.",
    expirationDate: daysFromNow(8),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "40% Off Creative Cloud — Limited Time",
      receivedAt: daysAgo(2),
      senderDomain: "adobe.com",
    },
    status: "active",
    qualityScore: 88,
    effectiveDiscountPercent: 40,
    notes: "All Apps plan included",
  },
  {
    id: "deal-008",
    retailer: "Target",
    retailerNormalized: "target",
    category: "Home & General Retail",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 20,
    discountUnit: "percent",
    promoCode: "TARGET20",
    minimumSpend: 50,
    restrictions: "Home & Kitchen category only. Online only.",
    expirationDate: daysFromNow(4),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "20% Off Home & Kitchen — Weekend Sale",
      receivedAt: daysAgo(1),
      senderDomain: "target.com",
    },
    status: "active",
    qualityScore: 82,
    effectiveDiscountPercent: 20,
    notes: "",
    brands: ["Dyson", "KitchenAid", "Instant Pot"],
  },
  {
    id: "deal-009",
    retailer: "Chipotle",
    retailerNormalized: "chipotle",
    category: "Fast Food & Restaurants",
    offerType: "freebie",
    dealColor: "teal",
    discountValue: 0,
    discountUnit: "free",
    promoCode: "FREEGUAC",
    minimumSpend: null,
    restrictions: "App orders only. One per account.",
    expirationDate: hoursFromNow(47),
    expirationStatus: "expiring_soon",
    urgency: "urgent",
    confidenceScore: "high",
    sourceEmail: {
      subject: "FREE Guacamole Today — App Exclusive",
      receivedAt: daysAgo(1),
      senderDomain: "chipotle.com",
    },
    status: "active",
    qualityScore: 85,
    effectiveDiscountPercent: 100,
    notes: "Free guacamole with any entrée",
  },
  {
    id: "deal-010",
    retailer: "Amazon",
    retailerNormalized: "amazon",
    category: "Tech & Electronics",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 35,
    discountUnit: "percent",
    promoCode: "PRIMEDAY35",
    minimumSpend: null,
    restrictions: "Prime members only. Select items.",
    expirationDate: hoursFromNow(12),
    expirationStatus: "expiring_soon",
    urgency: "urgent",
    confidenceScore: "high",
    sourceEmail: {
      subject: "Prime Day Lightning Deals — 35% Off Electronics",
      receivedAt: daysAgo(0),
      senderDomain: "amazon.com",
    },
    status: "active",
    qualityScore: 93,
    effectiveDiscountPercent: 35,
    notes: "Echo, Fire TV, Ring, and Kindle included",
    brands: ["Echo", "Fire TV", "Ring", "Kindle"],
  },
  {
    id: "deal-011",
    retailer: "Levi's",
    retailerNormalized: "levis",
    category: "Clothing & Apparel",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 30,
    discountUnit: "percent",
    promoCode: "SAVE30",
    minimumSpend: 75,
    restrictions: "Excludes sale items",
    expirationDate: daysFromNow(9),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "30% Off Your Next Purchase",
      receivedAt: daysAgo(3),
      senderDomain: "levi.com",
    },
    status: "active",
    qualityScore: 84,
    effectiveDiscountPercent: 30,
    notes: "",
  },
  {
    id: "deal-012",
    retailer: "Peloton",
    retailerNormalized: "peloton",
    category: "Health & Wellness",
    offerType: "dollar_off",
    dealColor: "orange",
    discountValue: 400,
    discountUnit: "dollars",
    promoCode: "PELOTONDEAL",
    minimumSpend: null,
    restrictions: "New members only. Bike or Tread purchase.",
    expirationDate: daysFromNow(14),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "medium",
    sourceEmail: {
      subject: "$400 Off Peloton Bike — Summer Fitness Sale",
      receivedAt: daysAgo(5),
      senderDomain: "pelotoncycle.com",
    },
    status: "active",
    qualityScore: 76,
    effectiveDiscountPercent: 20,
    notes: "",
  },
  {
    id: "deal-013",
    retailer: "Spotify",
    retailerNormalized: "spotify",
    category: "Subscriptions & SaaS",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 60,
    discountUnit: "percent",
    promoCode: null,
    minimumSpend: null,
    restrictions: "3 months at $2.99/mo for new subscribers.",
    expirationDate: null,
    expirationStatus: "no_expiry",
    urgency: "evergreen",
    confidenceScore: "medium",
    sourceEmail: {
      subject: "3 Months of Premium for $2.99/mo",
      receivedAt: daysAgo(7),
      senderDomain: "spotify.com",
    },
    status: "active",
    qualityScore: 71,
    effectiveDiscountPercent: 60,
    notes: "No expiry detected",
  },
  {
    id: "deal-014",
    retailer: "Expedia",
    retailerNormalized: "expedia",
    category: "Travel & Dining",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 25,
    discountUnit: "percent",
    promoCode: "TRAVEL25",
    minimumSpend: 500,
    restrictions: "Hotel bookings only. Non-refundable rate.",
    expirationDate: daysFromNow(7),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "25% Off Hotels This Summer",
      receivedAt: daysAgo(2),
      senderDomain: "expedia.com",
    },
    status: "active",
    qualityScore: 80,
    effectiveDiscountPercent: 25,
    notes: "",
  },
  {
    id: "deal-015",
    retailer: "Ulta Beauty",
    retailerNormalized: "ultabeauty",
    category: "Beauty & Cosmetics",
    offerType: "bogo",
    dealColor: "green",
    discountValue: 50,
    discountUnit: "bogo",
    promoCode: "BOGOULTA",
    minimumSpend: null,
    restrictions: "Select brands only. In-store and online.",
    expirationDate: daysFromNow(6),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "BOGO 50% Off Skincare — This Week Only",
      receivedAt: daysAgo(1),
      senderDomain: "ulta.com",
    },
    status: "active",
    qualityScore: 88,
    effectiveDiscountPercent: 50,
    notes: "",
    brands: ["CeraVe", "The Ordinary", "Neutrogena"],
  },
  {
    id: "deal-016",
    retailer: "Best Buy",
    retailerNormalized: "bestbuy",
    category: "Tech & Electronics",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 20,
    discountUnit: "percent",
    promoCode: "MYBESTBUY20",
    minimumSpend: 200,
    restrictions: "My Best Buy members only. TV and appliances excluded.",
    expirationDate: daysFromNow(2),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "Members Save 20% on Computers & Tablets",
      receivedAt: daysAgo(3),
      senderDomain: "bestbuy.com",
    },
    status: "active",
    qualityScore: 79,
    effectiveDiscountPercent: 20,
    notes: "",
    brands: ["Microsoft", "HP", "Samsung"],
  },
  {
    id: "deal-017",
    retailer: "HelloFresh",
    retailerNormalized: "hellofresh",
    category: "Grocery & Food",
    offerType: "dollar_off",
    dealColor: "orange",
    discountValue: 110,
    discountUnit: "dollars",
    promoCode: "FRESH110",
    minimumSpend: null,
    restrictions: "New subscribers only. $110 off first 5 boxes.",
    expirationDate: null,
    expirationStatus: "no_expiry",
    urgency: "evergreen",
    confidenceScore: "high",
    sourceEmail: {
      subject: "Get $110 Off Your First 5 HelloFresh Boxes",
      receivedAt: daysAgo(10),
      senderDomain: "hellofresh.com",
    },
    status: "active",
    qualityScore: 83,
    effectiveDiscountPercent: 55,
    notes: "",
  },
  {
    id: "deal-018",
    retailer: "REI",
    retailerNormalized: "rei",
    category: "Health & Wellness",
    offerType: "clearance_sale",
    dealColor: "yellow",
    discountValue: 40,
    discountUnit: "percent",
    promoCode: "REISALE",
    minimumSpend: null,
    restrictions: "Outlet items only. While supplies last.",
    expirationDate: daysFromNow(10),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "REI Outlet: Up to 40% Off Outdoor Gear",
      receivedAt: daysAgo(4),
      senderDomain: "rei.com",
    },
    status: "active",
    qualityScore: 81,
    effectiveDiscountPercent: 40,
    notes: "",
    brands: ["Patagonia", "The North Face", "Columbia"],
  },
  {
    id: "deal-019",
    retailer: "Wayfair",
    retailerNormalized: "wayfair",
    category: "Home & General Retail",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 15,
    discountUnit: "percent",
    promoCode: "WAY15HOME",
    minimumSpend: 299,
    restrictions: "Furniture only. Excludes mattresses.",
    expirationDate: daysFromNow(3),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "medium",
    sourceEmail: {
      subject: "15% Off Furniture — Refresh Your Space",
      receivedAt: daysAgo(2),
      senderDomain: "wayfair.com",
    },
    status: "active",
    qualityScore: 67,
    effectiveDiscountPercent: 15,
    notes: "",
  },
  {
    id: "deal-020",
    retailer: "Starbucks",
    retailerNormalized: "starbucks",
    category: "Fast Food & Restaurants",
    offerType: "bogo",
    dealColor: "green",
    discountValue: 50,
    discountUnit: "bogo",
    promoCode: null,
    minimumSpend: null,
    restrictions: "Happy Hour 2-7pm only. App required.",
    expirationDate: hoursFromNow(29),
    expirationStatus: "expiring_soon",
    urgency: "urgent",
    confidenceScore: "high",
    sourceEmail: {
      subject: "BOGO Happy Hour — Today 2-7PM",
      receivedAt: daysAgo(0),
      senderDomain: "starbucks.com",
    },
    status: "active",
    qualityScore: 90,
    effectiveDiscountPercent: 50,
    notes: "Any handcrafted beverage",
  },
  {
    id: "deal-021",
    retailer: "H&M",
    retailerNormalized: "hm",
    category: "Clothing & Apparel",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 20,
    discountUnit: "percent",
    promoCode: "HM20NOW",
    minimumSpend: null,
    restrictions: "Excludes H&M HOME and selected styles.",
    expirationDate: daysFromNow(1),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "20% Off Everything — Members Only Discount",
      receivedAt: daysAgo(1),
      senderDomain: "hm.com",
    },
    status: "active",
    qualityScore: 74,
    effectiveDiscountPercent: 20,
    notes: "",
  },
  {
    id: "deal-022",
    retailer: "Chewy",
    retailerNormalized: "chewy",
    category: "Home & General Retail",
    offerType: "free_shipping",
    dealColor: "teal",
    discountValue: 0,
    discountUnit: "free",
    promoCode: "SHIPFREE22",
    minimumSpend: 49,
    restrictions: "Auto-ship orders receive additional 35% off first order.",
    expirationDate: null,
    expirationStatus: "no_expiry",
    urgency: "evergreen",
    confidenceScore: "high",
    sourceEmail: {
      subject: "Free Shipping + 35% Off Auto-Ship",
      receivedAt: daysAgo(6),
      senderDomain: "chewy.com",
    },
    status: "active",
    qualityScore: 77,
    effectiveDiscountPercent: 35,
    notes: "",
  },
  {
    id: "deal-023",
    retailer: "Hulu",
    retailerNormalized: "hulu",
    category: "Subscriptions & SaaS",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 75,
    discountUnit: "percent",
    promoCode: null,
    minimumSpend: null,
    restrictions: "New subscribers only. $1.99/month for 12 months.",
    expirationDate: daysFromNow(20),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "Hulu: 75% Off for 12 Months — Limited Offer",
      receivedAt: daysAgo(5),
      senderDomain: "hulu.com",
    },
    status: "active",
    qualityScore: 91,
    effectiveDiscountPercent: 75,
    notes: "",
  },
  {
    id: "deal-024",
    retailer: "Gap",
    retailerNormalized: "gap",
    category: "Clothing & Apparel",
    offerType: "percentage_off",
    dealColor: "purple",
    discountValue: 50,
    discountUnit: "percent",
    promoCode: "GAPSUMMER",
    minimumSpend: null,
    restrictions: "Sale section items. Cannot stack with other offers.",
    expirationDate: daysFromNow(4),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "50% Off Summer Sale — Ends Sunday",
      receivedAt: daysAgo(2),
      senderDomain: "gap.com",
    },
    status: "active",
    qualityScore: 86,
    effectiveDiscountPercent: 50,
    notes: "",
  },
  {
    id: "deal-025",
    retailer: "CVS Pharmacy",
    retailerNormalized: "cvs",
    category: "Health & Wellness",
    offerType: "dollar_off",
    dealColor: "orange",
    discountValue: 10,
    discountUnit: "dollars",
    promoCode: "CVS10HEALTH",
    minimumSpend: 30,
    restrictions: "ExtraCare members only. Vitamins & supplements.",
    expirationDate: daysFromNow(7),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "medium",
    sourceEmail: {
      subject: "ExtraBucks: $10 Off $30 Vitamins Purchase",
      receivedAt: daysAgo(3),
      senderDomain: "cvs.com",
    },
    status: "active",
    qualityScore: 65,
    effectiveDiscountPercent: 33,
    notes: "",
  },
  {
    id: "deal-026",
    retailer: "Marriott",
    retailerNormalized: "marriott",
    category: "Travel & Dining",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 20,
    discountUnit: "percent",
    promoCode: "BONVOY20",
    minimumSpend: null,
    restrictions: "Bonvoy members. Advance purchase required.",
    expirationDate: daysFromNow(45),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "Save 20% with Advance Purchase Rate",
      receivedAt: daysAgo(8),
      senderDomain: "marriott.com",
    },
    status: "active",
    qualityScore: 72,
    effectiveDiscountPercent: 20,
    notes: "",
  },
  {
    id: "deal-027",
    retailer: "Sam's Club",
    retailerNormalized: "samsclub",
    category: "Grocery & Food",
    offerType: "clearance_sale",
    dealColor: "yellow",
    discountValue: 35,
    discountUnit: "percent",
    promoCode: null,
    minimumSpend: null,
    restrictions: "Members only. In-store only.",
    expirationDate: daysFromNow(1),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "low",
    sourceEmail: {
      subject: "Instant Savings — Member Only Offers",
      receivedAt: daysAgo(4),
      senderDomain: "samsclub.com",
    },
    status: "active",
    qualityScore: 52,
    effectiveDiscountPercent: 35,
    notes: "",
    codeInImage: true,
  },
  {
    id: "deal-028",
    retailer: "Lyft",
    retailerNormalized: "lyft",
    category: "Travel & Dining",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 50,
    discountUnit: "percent",
    promoCode: "RIDE50",
    minimumSpend: null,
    restrictions: "Next 3 rides. New users only.",
    expirationDate: daysFromNow(14),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "Welcome! 50% Off Your Next 3 Rides",
      receivedAt: daysAgo(1),
      senderDomain: "lyft.com",
    },
    status: "active",
    qualityScore: 88,
    effectiveDiscountPercent: 50,
    notes: "",
  },
  {
    id: "deal-029",
    retailer: "Microsoft",
    retailerNormalized: "microsoft",
    category: "Subscriptions & SaaS",
    offerType: "percentage_off",
    dealColor: "blue",
    discountValue: 30,
    discountUnit: "percent",
    promoCode: "MS365NOW",
    minimumSpend: null,
    restrictions: "Microsoft 365 Personal or Family. Annual plan.",
    expirationDate: daysFromNow(11),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "30% Off Microsoft 365 — Productivity Sale",
      receivedAt: daysAgo(4),
      senderDomain: "microsoft.com",
    },
    status: "active",
    qualityScore: 85,
    effectiveDiscountPercent: 30,
    notes: "",
  },
  {
    id: "deal-030",
    retailer: "Panda Express",
    retailerNormalized: "pandaexpress",
    category: "Fast Food & Restaurants",
    offerType: "freebie",
    dealColor: "teal",
    discountValue: 0,
    discountUnit: "free",
    promoCode: "PANDAFREE",
    minimumSpend: null,
    restrictions: "App orders only. Free entree with plate purchase.",
    expirationDate: daysFromNow(2),
    expirationStatus: "active",
    urgency: "normal",
    confidenceScore: "high",
    sourceEmail: {
      subject: "Free Entree with Your Next Plate — App Exclusive",
      receivedAt: daysAgo(2),
      senderDomain: "pandaexpress.com",
    },
    status: "active",
    qualityScore: 82,
    effectiveDiscountPercent: 40,
    notes: "",
  },
];

export function getActiveDeals(): Deal[] {
  return mockDeals.filter((d) => d.status === "active");
}

export function getExpiringDeals(): Deal[] {
  return mockDeals.filter((d) => d.urgency === "urgent" && d.status === "active");
}

export function getEvergreenDeals(): Deal[] {
  return mockDeals.filter((d) => d.urgency === "evergreen" && d.status === "active");
}

export function getTop10Deals(): Deal[] {
  return getActiveDeals()
    .filter((d) => d.urgency !== "evergreen" && d.expirationStatus !== "expired")
    .sort((a, b) => b.effectiveDiscountPercent - a.effectiveDiscountPercent)
    .slice(0, 10);
}

export function getDashboardStats() {
  const active = getActiveDeals();
  const categories = new Set(active.map((d) => d.category));
  const estimatedSavings = active.reduce((sum, d) => {
    if (d.discountUnit === "percent") return sum + d.discountValue * 5;
    if (d.discountUnit === "dollars") return sum + d.discountValue;
    return sum + 25;
  }, 0);

  return {
    totalActive: active.length,
    expiringToday: active.filter((d) => d.urgency === "urgent").length,
    categoriesCount: categories.size,
    estimatedSavings: Math.round(estimatedSavings),
  };
}
